import { getDecryptedApiKey } from '../store/aiStore'

interface GenerationResponse {
  content: string
  code: Array<{ name: string; content: string; language: string }>
  diagrams: Array<{ name: string; content: string }>
  instructions: string[]
  parts?: Array<{ name: string; quantity: number; description: string }>
  modelType?: string
}

export async function generatePrototype(productIdea: string, provider: string): Promise<GenerationResponse> {
  const apiKey = getDecryptedApiKey()
  
  if (!apiKey) {
    throw new Error('API key not configured')
  }

  const prompt = `You are Nyxer, an AI product prototyping assistant. Generate a complete prototype specification for:

${productIdea}

Respond with ONLY a JSON object (no markdown, no code blocks) with this exact structure:
{
  "content": "Brief description of what we're building",
  "code": [
    { "name": "filename.ext", "content": "full code content", "language": "javascript/python/c/arduino/etc" }
  ],
  "diagrams": [
    { "name": "diagram name", "content": "mermaid diagram code" }
  ],
  "instructions": [
    "Step 1: Do this...",
    "Step 2: Do that..."
  ],
  "parts": [
    { "name": "Component name", "quantity": 1, "description": "What it does" }
  ],
  "modelType": "simple/custom/hardware/robot/display"
}

For 3D model, describe what should be rendered (simple shapes for prototyping):
- "simple" = basic shapes
- "custom" = use primitives creatively
- "hardware" = circuit-like components
- "robot" = expressive robot face
- "display" = screen/device shape

Make it real and actionable.`

  if (provider === 'anthropic') {
    return generateWithAnthropic(apiKey, prompt, productIdea)
  } else if (provider === 'openai') {
    return generateWithOpenAI(apiKey, prompt, productIdea)
  } else {
    throw new Error(`Provider ${provider} not yet implemented`)
  }
}

async function generateWithAnthropic(apiKey: string, prompt: string, productIdea: string): Promise<GenerationResponse> {
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true'
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }]
    })
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`API error: ${response.status} - ${error}`)
  }

  const data = await response.json()
  return parseResponse(data.content[0].text, productIdea)
}

async function generateWithOpenAI(apiKey: string, prompt: string, productIdea: string): Promise<GenerationResponse> {
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'gpt-4o',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 4096
    })
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`API error: ${response.status} - ${error}`)
  }

  const data = await response.json()
  return parseResponse(data.choices[0].message.content, productIdea)
}

function parseResponse(content: string, productIdea: string): GenerationResponse {
  try {
    const cleaned = content.replace(/```json\n?|\n?```/g, '').trim()
    const parsed = JSON.parse(cleaned)
    
    return {
      content: parsed.content || `Building: ${productIdea}`,
      code: parsed.code || [],
      diagrams: parsed.diagrams || [],
      instructions: parsed.instructions || [],
      parts: parsed.parts || [],
      modelType: parsed.modelType || 'simple'
    }
  } catch {
    return generateFallback(productIdea)
  }
}

function generateFallback(productIdea: string): GenerationResponse {
  return {
    content: `Generating prototype for: ${productIdea}`,
    code: [
      {
        name: 'prototype.js',
        content: `// ${productIdea}\n// Generated by Nyxer_\n\nconst config = {\n  product: "${productIdea}",\n  version: "1.0.0",\n  features: []\n};\n\nexport default config;`,
        language: 'javascript'
      }
    ],
    diagrams: [
      {
        name: 'System Overview',
        content: `graph TD\n    A[Input] --> B[Processing] --> C[Output]`
      }
    ],
    instructions: [
      'Set up your development environment',
      'Copy the generated code',
      'Customize for your needs',
      'Deploy and test'
    ],
    parts: [
      { name: 'Microcontroller', quantity: 1, description: 'Main processing unit' },
      { name: 'Power Supply', quantity: 1, description: '5V USB or battery' }
    ],
    modelType: 'simple'
  }
}
